### ISSUE TITLE
Unable to determine what selector triggers $.fn.wc_variation_form; no longer triggered in 2.5.2

### ISSUE THREAD

**Issue by indextwo** [woothemes/woocommerce#10375]
I'll preface this by saying that I have been working on a fairly unique build, and as per the client's requirements, a lot of the functionality is highly custom. However, it's all in plugins or in the theme, and I haven't modified any of the core. I have been able to narrow this issue down to a difference between WC 2.4.12 and WC 2.5.2.

With that in mind: the site has worked fine for a little over 2 years with only minor updates needed. However, today I did an upgrade from WC 2.4.12 to 2.5.2, and, to cut a long story short, it looks like the `wc_variation_form` JS plugin function defined in `assets/js/frontend/add-to-cart-variation.js` is no longer getting fired when a product is loaded via ajax.

I am using a number of custom templates, including the key one in this case (which I believe is `/single-product/add-to-cart/variable.php`). Because of the client's requirements, many different types of product are all listed on a single page, and each of those has hundreds of variations. As a consequence, when someone clicks on a product, it is loaded via ajax into a lightbox and a `getScript` call is made on the relevant scripts (including `add-to-cart-variation.js`). Because of the client's very specific requirements, the variation field values are all triggered and changed via jQuery as the customer makes certain selections, and the key trigger was when updating a 'core' dropdown with the appropriate attribute values and variation ID. At the point that a customer made their necessary selection, an ajax POST - `/?wc-ajax=get_variation` - would be made with those values, return the appropriate object information, and then display the price and 'Add to Cart' button. As mentioned, this all worked perfectly up until my update to 2.5.2.

It took me hours to track down, but it does appear that the main function in that file - `$.fn.wc_variation_form` - is no longer triggered for my ajaxified product form. This appears to be what handles the product attribute changes in the form, and without this being triggered, that `/?wc-ajax=get_variation` function is never fired.

Suspecting it was an issue with a selector (since the `variable` template has been updated between 2.4 and 2.5), I restored the core 2.5.0 version of the file from `/woocommerce/templates/`, but to no effect. I then reasoned that I could manually trigger the function once the ajax load had successfully completed:

    $varForm = $('#productcontents').find('form.variations_form');
    $varForm.trigger('wc_variation_form');

However, that doesn't appear to work either.

I temporarily modified the core `add-to-cart-variation.js` file to output a successful trigger to the console. If I load & view a product via ajax with Woo 2.4.12 installed and that `console.log()` modification, it outputs successfully (`'I am a form, and I have been PLUGGED IN!'`); but if I try the same with Woo 2.5.2, I get nothing. Interestingly, trying to trigger it manually (as above) doesn't work in either version, so I assume I'm missing something there.

Is there anything glaring obvious that I'm missing, or has a significant change been made to the way this JS function is triggered?

**Comment by indextwo** [comment]
So I 'solved' this, but I'm not entirely comfortable with the fix.

In the end I tried to directly trigger the function on the form with `$varForm.wc_variation_form();` but that resulted in the JS error `wp.template is not a function`. Thanks to [this post on StackOverflow](http://stackoverflow.com/questions/35203936/modify-woocommerce-javascript) I realised that the global `wp` and associated functions were included via `wp-util.js`, so I just enqueued that script, and it _almost_ worked; the form was finally recognised and I could successfully trigger `wc_variation_form` against it, but as soon as I selected a new variation, I got 'TypeError: n is undefined' thrown by `underscore.js`.

So, in the end I dequeued WC's `add-to-cart-variation.js`, took a copy of that same file from WC 2.4.12, copied it to my theme and enqueued that. All of my problems have disappeared!

I'm mildly concerned that this will break things in the future when there's another WC update, but in the meantime this works for the client. I just wish I knew _why_ `wc_variation_form` wasn't being automatically triggered in the first place, when it had worked perfectly in WC 2.4.12.

**Comment by mikejolley** [comment]
Confirmed that wc_variations_form is ran regardless of whether ajax is used or not.

`
	$( function() {
		if ( typeof wc_add_to_cart_variation_params !== 'undefined' ) {
			$( '.variations_form' ).each( function() {
				$( this ).wc_variation_form().find('.variations select:eq(0)').change();
			});
		}
	});
`

There is no check for ajax or not.

Based on your wp.template error, I presume you're missing dependencies which is why things are not firing correctly. I saw another user with similar issue but looked to be a conflict/old version of WP issue. wp-util.js should be enqueued - if its missing, the script will fail.

`
self::register_script( 'wc-add-to-cart-variation', $frontend_script_path . 'add-to-cart-variation' . $suffix . '.js', array( 'jquery', 'wp-util' ) );
`

Adding wp-util dependency was a recent fix.
