### ISSUE TITLE
Analytics dashboard crash ( tz is not a function ) due to plugin conflict with moment.js

### ISSUE THREAD

**Issue by chihsuan** [woothemes/woocommerce#64020]
## Context

A [forum report](<https://wordpress.org/support/topic/bug-woocommerce-10-6-1-analytics-dashboard-crash-tz-is-not-a-function/>) shows Analytics dashboards crashing with `TypeError: tz is not a function` in WooCommerce 10.6.1.

Root cause: a third-party plugin clobbers the global `window.moment` after WooCommerce's bundle loads, removing the `.tz()` method added by `moment-timezone`. This was latent but surfaced by woocommerce/woocommerce#62872 (10.6.0), which expanded the conditions under which `.tz()` is called.

## Proposed fix

In `packages/js/date/src/index.ts` → `getStoreTimeZoneMoment()`, use the bundled `momentTz` import directly instead of casting the global `moment()` instance. Since `momentTz` is bundled (not externalized), it won't be affected by plugins replacing `window.moment`.

## References

* [Forum thread](<https://wordpress.org/support/topic/bug-woocommerce-10-6-1-analytics-dashboard-crash-tz-is-not-a-function/>)
* Bug introduced in PR #62872

**Comment by frankremmy** [comment]
Just a note on how a merchant from the forum managed to solve this even after an update. 

> I managed to resolve this issue. Seems like with the latest updates of woocommerce, “moment” is loaded however we still missing the extension. “moment-timezone-with-data” I added the following into functions.php. Hopefully you and your team can look into this.

```php
add_action( ‘admin_enqueue_scripts’, function() {

wp_enqueue_script(
    'moment-timezone',
    'https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.43/moment-timezone-with-data.min.js',
    array( 'moment' ),
    '0.5.43',
    true
);
}, 1 );
``` 

[Forum thread](https://wordpress.org/support/topic/analytics-tab-oops-something-went-wrong/#post-18945694)

**Comment by tauclement** [comment]
I updated to 10.8.1 and still experienced the error. below is the code fix i used.

add_action( ‘admin_enqueue_scripts’, function() {

wp_enqueue_script(
    'moment-timezone',
    'https://cdnjs.cloudflare.com/ajax/libs/moment-timezone/0.5.43/moment-timezone-with-data.min.js',
    array( 'moment' ),
    '0.5.43',
    true
);
}, 1 );

**Comment by chihsuan** [comment]
Thanks everyone for the detailed reports and for sharing your workarounds here — they were a big help in tracking down what's going on. 🙏

**Why the earlier fix didn't make the problem go away**

The fix in #64021 worked by giving WooCommerce its **own private copy** of the timezone tool, so it couldn't be broken by other plugins.

A later change, #64201 (which fixed some unrelated console warnings), switched WooCommerce **back to sharing WordPress's global timezone tool**. That's the same tool a conflicting plugin overwrites — so when that happens, WooCommerce loses the timezone function again and Analytics crashes with `tz is not a function`. The two changes work against each other, and the second one effectively undid the first.

#64201 did include a test meant to confirm the fix still worked, but the way it *simulated* a plugin conflict didn't match what real plugins do, so the test passed even though the bug was back.

This is also why the workaround several of you posted works: re-adding `moment-timezone` restores the missing function on the shared tool.

**Next step:** a proper fix needs to either give WooCommerce a private timezone copy again (without re-triggering the console-warning issue #64201 solved) or stop relying on the shared global altogether. A new test should reproduce a *real* plugin conflict so this can't silently regress again.

Thanks again for your patience — we'll get this sorted.
